server:
  port: 8080
  address: 0.0.0.0
spring:
  application:
    name: "Authentication"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

routes:
  paths:
    users: "/api/v1/users"
    emailExists: "/api/v1/users/exists/{email}"
    userEmail: "/api/v1/users/email/{email}"
    login: "/api/v1/users/login"


adapters:
  r2dbc:
    host: ${R2DBC_HOST}
    port: ${R2DBC_PORT}
    database: ${R2DBC_DATABASE}
    schema: ${R2DBC_SCHEMA}
    username: ${R2DBC_USERNAME}
    password: ${R2DBC_PASSWORD}

security:
  jwt:
    expiration: 3600000
    public-key-location: file:${JWT_PUBLIC_KEY}
    private-key-location:  file:${JWT_PRIVATE_KEY}