server:
  port: 8080
  servlet:
    context-path: /auth
spring:
  application:
    name: "Authentication"
  devtools:
    add-properties: false
  profiles:
    include: null
management:
  endpoints:
    web:
      base-path: /auth/actuator
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

routes:
  paths:
    users: "/auth/api/v1/users"
    emailExists: "/auth/api/v1/users/exists/{email}"
    userEmail: "/auth/api/v1/users/email/{email}"
    login: "/auth/api/v1/users/login"

springdoc:
  swagger-ui:
    path: /auth/swagger-ui
  api-docs:
    path: /auth/v3/api-docs
  packages-to-scan:
    - co.com.crediya
  paths-to-match:
    - /**

adapters:
  r2dbc:
    host: ${R2DBC_HOST}
    port: ${R2DBC_PORT}
    database: ${R2DBC_DATABASE}
    schema: ${R2DBC_SCHEMA:public}
    username: ${R2DBC_USERNAME}
    password: ${R2DBC_PASSWORD}
security:
  jwt:
    expiration: 3600000
    public-key-location: ${JWT_PUBLIC_KEY}
    private-key-location:  ${JWT_PRIVATE_KEY}