server:
  port: 8080
spring:
  application:
    name: "Authentication"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

routes:
  paths:
    users: "/api/v1/users"
    emailExists: "/api/v1/users/exists/{email}"
    login: "/api/v1/users/login"

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "test"
    schema: "sm"
    username: "sm"
    password: "1234"
    #url: "r2dbc:mysql://localhost:3306/users"
    #username: root
    #password: 1234
    #sql:
    #  init:
    #    mode: always
    #flyway:
    #  enabled: false

security:
  jwt:
    expiration: 3000 #3600000
    public-key-location: classpath:public_key.pem
    private-key-location: classpath:private_key.pem